egoist/tsup

README.md
src/utils.ts

This PR will auto externalize `peerDependencies` as the same as `dependencies`. For most of the cases, it makes sense for libraries to not bundle their `peerDependencies`.

feat: externalize `peerDependencies`

---

package.json
src/cli.ts
src/index.ts
test/index.test.ts
yarn.lock

I was thinking that tsup is a good alternative to [tsc-watch](https://github.com/gilamran/tsc-watch) while using watch mode, but it definitely needed at least the "onSuccess", maybe more lifecycles could be added after

feat: add `--onSuccess <command>` flag

---

src/cli.ts
src/errors.ts
src/index.ts
src/rollup.ts

While playing with it I realized two thing:
- If a build error happens on watch-mode, the process is killed because the promise is not being catched
- It's better to kill the previous onSuccess process as early as possible to give the OS more time to kill the process for the new process to not overlap

fix watch catch error, earlier prev process kill

---

docs/README.md
src/cli.ts
src/index.ts

Added **--ignore-watch,** since after changing the watching, in a project with runtime code-generation it basically breaks because of not being able to ignore them.
And added some docs about --ignore-watch & onSuccess

add ignoreWatch & docs

---

package.json
pnpm-lock.yaml
src/index.ts

while using it in Windows I realized the previous killing process is unreliable, in MacOS it was fine, but windows was the issue.
[tree-kill](https://www.npmjs.com/package/tree-kill) doesn't have any dependency, and doing a global require shouldn't have any impact, but using a dynamic import is possible

use tree-kill

---

docs/README.md
src/index.ts
src/load.ts
src/rollup.ts
src/utils.ts

- I separated the load logic into its own module since I don't think they are not just utils
- Added support for using a `tsup` property inside the `package.json`
- While implementing it I figured out that using a possible "tsup" export from the file is also useful, since it enables a one-line export with `export const tsup: Options = `, or using `exports.tsup =` in plain js.
- Added docs about this feature
closes #300

Improve file config load & add docs

---

src/index.ts

Right now the `silent` config is ignored since the `setSilent` is called before the config resolution, this is a small fix for that

respect silent config

---

src/index.ts

I realized that the `setSilent` is being called a little later than it should, and it's missing a couple of logs to be silenced:

fix: call setSilent earlier

---

src/index.ts

- allow to disable esbuild bundle option
- allow to add clean patterns
```ts
export default defineConfig({
bundle: false,
clean: ['!build/*', '!.cache']
});
```

make build option more flexible

---

src/esbuild/external.ts
src/esbuild/index.ts
src/esbuild/node-protocol.ts
test/index.test.ts

Bundling a dependency with `import fs from 'node:fs'` didn't work with Node v12 because it would convert the import statement to a `require`, which requires Node v14.18.0.
- Add a simple esbuild plugin to strip the `node:` protocol
- Remove the `disabled` option in `externalPlugin` in favor of not passing it into esbuild in the first place. Minor performance nitpick since I didn't want to have two different ways of disabling plugins.

feat(minor): support `node:` import in older node versions

---

package-lock.json
package.json
src/cli-main.ts
test/index.test.ts

On Windows, the terminal always includes the backslash when auto-completing paths

fix(windows): support backslash in cli arguments

---

.github/workflows/nodejs.yml
package-lock.json
package.json
src/cli-main.ts
src/index.ts
src/load.ts
src/utils.ts

fix(windows): normalize path in watcher

---

src/esbuild/index.ts

Maybe we can use [deno_std](https://github.com/denoland/deno_std) to make shim work in both node and browser.
file url to path: https://github.com/denoland/deno_std/blob/76d8c0159b72f5fa27f605c085dacfe236ffa54c/path/posix.ts#L493
basename: https://github.com/denoland/deno_std/blob/76d8c0159b72f5fa27f605c085dacfe236ffa54c/path/posix.ts#L249

fix: only use esm shim for node platform

---

docs/README.md
docs/index.html
package.json
pnpm-lock.yaml
src/cli-main.ts
src/esbuild/index.ts
src/esbuild/postcss.ts
src/fs.ts
src/index.ts
src/options.ts
src/plugin.ts
src/plugins/cjs-splitting.ts
src/plugins/es5.ts
src/plugins/shebang.ts
src/utils.ts
test/index.test.ts
types.d.ts

This implements a tsup plugin system (not esbuild):
- For now it's for internal use, I'm refactoring some code to plugins
- For now I only added a `renderChunk` hook which runs against each output js/css file
- No more babel, nobody uses it with tsup (it also runs after esbuild, not sure why I made that decision in the first place)
- ~~No more buble too, who needs es5?~~ 🧐

feat: experimental plugin system

---

src/index.ts
test/index.test.ts

style should be bundled into all format files if `option.injectStyle` specified.

fix: inject style in multi formats

---

src/plugin.ts

At the moment `.css` files generated when the `sourcemap` flag is `true` have a sourcemap comment at the bottom of the file that makes the file invalid:
`//# sourceMappingURL=index.css.map`
As indicated in the MDN [docs](https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Use_a_source_map) and the [specification](https://sourcemaps.info/spec.html#h.lmz475t4mvbx) for source map, the comment pointing to the source map for CSS files needs to use the `/*# sourceMappingURL=/path/to/sourcemap.map */` syntax.
This PR should create a valid sourcemap comment for both `.css` and `.js` files. Feel free to adjust the code to fit whatever style makes the most sense for your library.
And of course, thank you for the fantastic library. Exceptionally useful.

fix: Fix broken sourcemap comment generation for `.css` files

---

src/esbuild/index.ts

Currently, `noExternal` has no effect.

fix: Pass noExternal to externalPlugin

---

src/index.ts

After the build fails, buildDependencies has been cleared, so the watch cannot continue. Need to restore the previous buildDependencies after the build fails

fix: buildDependencies lost after build failure

---

src/index.ts
src/rollup.ts

Fix https://github.com/egoist/tsup/issues/562
I tried to fix this. All tests are passed.
The fixes are
- make parentPort postMessage before close
- make dts build a promise

fix: build promise resolves before types are emitted

---

package.json
pnpm-lock.yaml

Hi there,
Not sure if this will truly be helpful or not, but wanted to try.
I've run into an issue in building out a new library with `tsup` where the pinned version of `rollup-plugin-dts` doesn't support types with negative numbers as keys, such as:
```ts
type Foo = {
[-1]: string
}
```
I ran into this trying to setup a design system library with https://vanilla-extract.style. 
I've setup a minimal reproduction of the issue here: https://github.com/oscarnewman/tsup-repro
In my testing, updating `rollup-plugin-dts` (and `rollup` as is required by it's new peer-dep version) fixes this issue, and the test suite passes locally for me.
We've currently just switched to running a fork with these updates at `@oscarnewman/tsup` but would love to help out anyone else who's also faced this issue.

chore(deps): Update `rollup` and `rollup-plugin-dts` to latest versions

---

src/esbuild/index.ts
src/log.ts

I don't know if you did it here on purpose or forgot to modify it. When I set `silent: true`, some esbuild warning messages are still printed. I felt it was a bug and therefore fixed it.
Also, if we don't pay attention to the format of the print, can we use `Logger` to print esbuild warning messages, which can reduce the dependence of `consola`. 🙂

fix: ignore esbuild warning if silent is true

---

package.json
pnpm-lock.yaml
src/index.ts
test/index.test.ts

Hello,
I activated the `shell` option for executing commands passed to `onSuccess`. It allows for more complicated commands and workflows.
A very concrete use-case is to reboot a web server after the build is done:
```json
{
"scripts": {
"dev": "tsup src/index.ts --format esm,cjs --clean --watch src --onSuccess 'pnpm build:types && kill-port 4000 && pnpm start'",
"build": "tsup src/index.ts --format esm,cjs --clean --onSuccess 'pnpm build:types'",
"build:types": "tsc --project tsconfig.build.json --emitDeclarationOnly --declaration --declarationMap",
"start": "node ./dist/index.js",
}
}
```
Sorry for the code format changes but it seems like prettier wasn't run on dev?

feat(minor): use shell option for complex commands in onSuccess

---

src/index.ts

As described in #667, `outExtension` and `dts` do not work well together. This PR seems to fix that.

fix: fix `DataCloneError` when DTS is on

---

docs/README.md
src/index.ts
src/options.ts
test/index.test.ts

Resolves #637
Allows onSuccess to be a `function` as well as `string`. This option is only available from tsup config file (`tsup.config.ts`) for an obvious reason.
Had to do some little extra work to cancel the promise from `onSuccess` function because `otherTasks()` is used in watch mode which needs to cancel the previous process (= promise) when there's a fresh run caused by a file change. The majority of changes to `src/index.ts` attributes to that.

feat: allow onSuccess callback in tsup config file

---

src/index.ts
src/options.ts
src/rollup.ts

I'm a little confused. Since we have `loadTsConfig`, why we still load the config from `loadCompilerOptions`? I think we can parse it directly.

feat: add option to override tsconfig

---

src/rollup.ts

Fixes https://github.com/egoist/tsup/issues/680
By moving the `handleError` to occur before `logger.error`, the underlying error can be logged to the console, instead of being swallowed.

Log rollup errors

---

src/index.ts
src/plugins/tree-shaking.ts

Supplement to the #643.
When I set `silent: true` and `treeshake: true`, some rollup messages are still printed.

fix: ignore rollup warning if silent is true

---

docs/README.md
src/cli-main.ts
src/esbuild/index.ts
test/__snapshots__/index.test.ts.snap
test/index.test.ts

`external` now support to exclude special `package.json`'s `dependencies` and `peerDependencies`.
motivation: In monorepo, some `dependencies` are written as public in `package.json` under the workspace, and now users can specify special `package.json` to exclude them.

feat: allow to exclude dependencies from specific package.json

---

docs/README.md
src/esbuild/external.ts
src/options.ts
test/__snapshots__/index.test.ts.snap
test/index.test.ts

Fixes #718 
/!\ I haven't tested if it still builds (but I only touched 2 lines of code) + this might be a slight breaking change if some people use `tsup-node` and accidentally had a  "noExternal" option set (before this PR, the noExternal would be ignored, after this PR, it is correctly considered thus bundling more packages).

fix: respect noExternal option with Tsup node

---

src/rollup.ts
test/__snapshots__/index.test.ts.snap
test/index.test.ts

This PR fixes an issue with `--dts-resolve`.
When relying on types coming `from 'some-package/some-subpath'`, anything that is not imported `from 'some-package'` would end up getting unnecessarily bundled into the emitted `.d.ts` bundle.
It seems we were configuring Rollup's `external` with exact package names.
Here we're adjusting to use the same regex approach taken with esbuild:
https://github.com/egoist/tsup/blob/d074dd9c33adf85bcd149e79c9d141517a956ce0/src/esbuild/index.ts#L80-L81

fix: Configure Rollup's external to support subpaths too

---

src/cli-main.ts
src/esbuild/index.ts
src/index.ts
src/load.ts
src/rollup.ts
src/utils.ts
test/__snapshots__/index.test.ts.snap

feat: rebuild when package.json dependencies changed

---

src/index.ts

See https://github.com/egoist/tsup/pull/746 for my initial confusion. I generate my types through a separate process (manual `tsc` invocation), and was confused when `clean: true` was not removing them when running tsup.

fix: clean d.ts files if "dts" option is false

---

src/index.ts
src/log.ts

resolve #776 
use `parentPort.postMessage` as a workaround for `console.log` in worker thread ~

fix: use postMessage instead of console in worker thread

---

docs/README.md
package.json
schema.json

Touched on this briefly in https://github.com/egoist/tsup/issues/654 
This will allow users to easily extend  intellisense capabilities to the `package.json` file if choosing to pass configurations this way. Users working with vscode or an editor which support the JSON Language Server can optionally choose to implement this.
Consumers will need to point to `https://unpkg.com/tsup/schema.json` if they choose to leverage the feature within their editor.

Provide JSON Schema Store 

---

.gitignore
docs/README.md
package.json
pnpm-lock.yaml
src/cli-main.ts
src/esbuild/index.ts
src/index.ts
src/options.ts
src/plugins/terser.ts

Related to issue https://github.com/egoist/tsup/issues/742
This adds optional terser minification support by allowing `minify: 'terser'` and an optional `terserOptions` property in config.
Setting `minify: 'terser'` uses terser to minify, and emits the proper code and sourcemaps. I have used this on my package neodrag which has 2 modules, and it emits same sized outputs.
Gonna keep this as draft for now to figure out the API surface and potential bugs

feat: Minify with terser

---

src/plugins/tree-shaking.ts
test/index.test.ts
test/package.json
test/pnpm-lock.yaml

Fixes #814
rollup v3 changed the interop behavior: https://rollupjs.org/guide/en/#outputinterop
> Note that the default mode of `"default"` mimics NodeJS behavior and is different from TypeScript esModuleInterop. To get TypeScript's behavior, explicitly set the value to `"auto"`. In the examples, we will be using the CommonJS format, but the choice of interop similarly applies to AMD, IIFE and UMD targets as well.
Component
```tsx
import ReactSelect from 'react-select'
export const Component = (props: {}) => {
return <ReactSelect {...props} />
};
```
`tsup` flags
```bash
--treeshake --target es2022 --format cjs
```
`tsconfig`
```json
{
"compilerOptions": {
"baseUrl": ".",
"esModuleInterop": true,
"isolatedModules": true,
"jsx": "react-jsx",
"lib": ["dom", "dom.iterable", "esnext"], …
```

fix: default exports not working on CJS + treeshake: true

---

package.json
pnpm-lock.yaml
src/rollup.ts
test/index.test.ts

close #762 
close #791 
update `rollup-plugin-dts` to latest version:
* respect custom tsconfig option in `tsup.config.ts` 
* generate `export {}` for input file that have no exports.

feat: update rollup-plugin-dts to support custom tsconfig and preserve export {} for file that have no exports

---

src/options.ts

Feel free to tweak this, this should allow better autocomplete. 👍 
This allows both the suggested strings or any string the user wants in case their target isn't in the list.

feat(types): allow autocomplete for target

---

package.json
pnpm-lock.yaml

after falsely reporting #833, i discovered the underlying issue was actually in rollup-plugin-dts (https://github.com/Swatinem/rollup-plugin-dts/issues/248) and subsequently open a PR to fix it (https://github.com/Swatinem/rollup-plugin-dts/pull/249)
just gotta bump the version here and watch mode should work pretty flawlessly for `.d.ts` builds now!

fix: upgrade rollup-plugin-dts for better watch mode support

---

docs/README.md
docs/index.html

Unfortunately, the documentation site is not loading today because unpkg is down again.
See issues: 
- https://github.com/mjackson/unpkg/issues/352
- https://github.com/mjackson/unpkg/issues/343
- https://github.com/mjackson/unpkg/issues/338

chore(docs): using jsdelivr insted of unpkg

---

src/esbuild/postcss.ts
src/options.ts
test/index.test.ts

Support setting `options.injectStyle` as a function that returns JS code to add CSS in a custom way, like [rollup-plugin-postcss](https://github.com/egoist/rollup-plugin-postcss#inject).
This can be used in some cases such as when adding styles to shadowRoot:
```
export defineConfig({
injectStyle: (css) => {
return `
var setStyle = function() {
setTimeout(() => {
try {
var style = document.createElement('style');
style.type = 'text/css';
style.innerHTML = ${css};
var root = document.getElementsByTagName('${tag}')[0].shadowRoot;
root.insertBefore(style);
} catch {
setStyle()
}
},1000)
};
setStyle();
`;
},
})
```

feat: add function type for options.injectStyle

---

package.json
pnpm-lock.yaml

Adds support for [TS 5.0](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0)'s new syntax, part of #858
This PR doesn't add support for [mentioning multiple files in `extends`](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#supporting-multiple-configuration-files-in-extends), so #849 wouldn't get fixed by this
<details><summary>Testing</summary>
<p>
```ts
export function loggedMethod(originalMethod: any, _context: any) {
function replacementMethod(this: any, ...args: any[]) {
console.log("LOG: Entering method.")
const result = originalMethod.call(this, ...args);
console.log("LOG: Exiting method.")
return result;
}
return replacementMethod;
}
export class Person {
name: string;
constructor(name: string) {
this.name = name;
}
@loggedMethod
greet() { …
```

feat: support typescript 5.0 new syntax

---

src/options.ts

This types Options.format as `Format[] | Format` instead of `Format[] | string`.
You can currently pass in an array or string to `format`, however, the type is not consistent, as you are allowed to use the string literals from `Format` only for arrays, but not for strings. Typing it as `string` allows you to put anything as an option. This fixes that.

refactor(options)!: type format as Format

---

src/esbuild/external.ts

This PR fixes the regex used to match non node modules in the esbuild external plugin.
It changes the regex to match on the root of a windows-based filesystem in addition to simplifying the match of a unix-like root or relative path. 
This inverts the logic, however, I believe the regex was improperly named before, as what it was matching was actually node modules.
- By happenstance, this also fixes #879 and fixes #844.
- However, a more proper fix can be made if https://github.com/evanw/esbuild/issues/3079 gets implemented.

fix(external): match root paths on unix-like and windows

---

src/index.ts
src/plugins/terser.ts

The terser log was not prefixed with name. This PR fixes that.
```
[TSUP] CLI Building entry: src/cli-default.ts, src/cli-main.ts, src/cli-node.ts
[TSUP] CLI Using tsconfig: tsconfig.json
[TSUP] CLI tsup v0.0.0-semantic-release
[TSUP] CLI Using tsup config: C:\Users\green\Documents\GitHub\tsup\tsup.config.ts
[TSUP] CLI Target: node14
[TSUP] CJS Build start
TERSER Minifying with Terser
TERSER Terser Minification success
TERSER Minifying with Terser
TERSER Terser Minification success
TERSER Minifying with Terser
TERSER Terser Minification success
[TSUP] DTS Build start
[TSUP] CJS dist\cli-main.js    103.91 KB
[TSUP] CJS dist\cli-default.js 103.95 KB
[TSUP] CJS dist\cli-node.js    103.98 KB
[TSUP] CJS ⚡️ Build success in 1241ms
[TSUP] DTS ⚡️ Build success in 2368ms
[TSUP] DTS dist\index.d.ts …
```

fix: prefix terser log with name

---

src/index.ts
src/plugins/terser.ts
test/index.test.ts

When `globalName: 'globalFoo'` is set and the output format is `iife`, the output for the following input was not correct.
The variable `globalFoo` is not declared in the output.
```js
// input
export default 'foo'
// output (formatted)
'use strict'
;(() => {
var e = Object.defineProperty,
t = Object.getOwnPropertyDescriptor,
r = Object.getOwnPropertyNames,
o = Object.prototype.hasOwnProperty,
a = {}
;((t, r) => {
for (var o in r) e(t, o, { get: r[o], enumerable: !0 })
})(a, { default: () => n })
var f,
n = 'foo'
;(f = a),
((a, f, n, c) => {
if ((f && 'object' == typeof f) || 'function' == typeof f)
for (let l of r(f))
o.call(a, l) ||
l === n ||
e(a, l, {
get: () => f[l],
enumerable: !(c = t(f, l)) || c.enumerable,
})
})(e({}, '__esModule', { value: !0 }), f)
})()
```
This PR fixes this …

fix: preserve top-level when running terser for IIFE

---

src/plugins/es5.ts

This PR fixes an issue when targeting `es5` and using `terser` for minification.
Currently when `minify === true` in `tsup` options, `SWC` will mangle the code. It leads to unexpected behavior, as you would believe that you have fine-grained control with `Terser`.

Remove SWC and Terser minification clash

---

schema.json

schema.json still used egoist.sh in one place which seems to be an ad domain now.

Update docs domain in schema.json

---

docs/README.md

Making it a bit more obvious that the `--entry.*` parameter is intended to customize the output file names. 
(Ref. https://github.com/egoist/tsup/issues/447)

Clarify definition of custom output file names in docs

---

docs/README.md
src/cli-main.ts
src/index.ts
src/options.ts
src/plugins/cjs-interop.ts
src/rollup.ts

Introduce a new option `cjsInterop`.
In the CJS file, if there's only an export default, then make it to `module.exports = _default`, instead of `module.exports = { default: _default }`.
For dts files, it will replace `export { _default as default }` with `export = _default`
```ts
// before
const mod = require('something').default
// after
const mod = require('something')
```
Closes #572
It would be really helpful for removing [tons of post-build scripts](https://github.com/search?q=code+%2B%3D+%27exports.default+%3D+module.exports%3B%27&type=code).
`sucrase` also had an option [`enableLegacyBabel5ModuleInterop`](https://github.com/alangpierce/sucrase#legacy-commonjs-interop), with the same effect.

feat: add option for interop default in cjs

---

src/esbuild/postcss.ts
test/__snapshots__/index.test.ts.snap
test/index.test.ts
test/package.json
test/pnpm-lock.yaml

In #983, which is not released yet, I accidentally removed the `await` before `postcss`. This causes some async PostCSS plugins to throw errors, for example, TailwindCSS. 
This PR fixes the bug by adding the `async` back, and also adds a test case with PostCSS and TailwindCSS.

fix: await postcss for async plugins

---

src/rollup.ts
test/index.test.ts

- Followup to https://github.com/egoist/tsup/pull/934
For runs with multiple entrypoints, there will sometimes be chunks generated.  Currently, the chunks generated *always* output .d.ts regardless of format, since that is rollup-plugin-dts's default. The prior PR fixed this for the main bundle output, but not these chunks.
In a lot of cases, this would be a non issue. However, in certain cases, a type is determined to be "internal" even though typescript can see through to the expected type. Because this file ends in `.ts`, it finds the nearest package.json to determine the module type (lets say cjs for this example). If this "internal" type is imported from another package with dual exports (say for something that's a peer dep), and then imported in application code that is another type …

fix(dts): ensure chunks conform to bundle format

---

src/api-extractor.ts
test/__snapshots__/index.test.ts.snap
test/index.test.ts

This PR fixes a bug when using the `--experimental-dts`.
Let's say we have the following file structure:
```
// src/shared.ts
export const declare1 = 'declare1'
export const declare2 = 'declare2'
// src/entry1.ts
export { declare1 } from './shared'
// src/entry2.ts
export { declare2 } from './shared'
```
In this example, `entry1.ts` and `entry2.ts` are public entry files. In the generated `entry1.d.ts`, it should only contain `declare1`, and `entry2.d.ts` should only contain `declare2`. However, the generated `entry1.d.ts` and `entry2.d.ts` incorrectly contain both `declare1` and `declare2`.
This PR fixes this bug and adds a test case.

fix(experimental-dts): only include exported declarations

---

src/api-extractor.ts
src/index.ts
test/index.test.ts

Closes https://github.com/egoist/tsup/issues/1040

fix(experimental-dts): make `--experimental-dts` to be compatible with `--clean`

---

src/plugins/swc-target.ts

If it is mjs, it is not included in the swcTarget even if I set it as an ES5 target.
I think the reason for the exclusion of mjs is that if the browser supports import, it is guaranteed to run ES6 or later code.
However, if you use a process like the one below, you'll run into problems.
- generate cjs, mjs code for target: es5 with tsup and publish it as a package named foo.
- a project named bar installs and uses the foo package. This project is set "type": "module".
- the bar project has imported the foo package.
- the bar project runs with ESM, it reads foo/index.mjs.
- when we build the bar project, the foo package is in node_modules, so it won't run in older browsers unless we transpile it further.
In addition to this issue, I think it's also a problem that tsup's target is set to …

fix: support swc target for mjs

---

src/plugin.ts
src/plugins/tree-shaking.ts
test/index.test.ts

depends on pr https://github.com/egoist/tsup/pull/890
related to issue https://github.com/egoist/tsup/issues/889#issuecomment-1871297831
1. fix incorrect use of `applySourceMap()`
correct example: https://github.com/mozilla/source-map/blob/master/test/test-source-map-generator.js#L356-L362
2. set rollup treeshake output path to `./dist`, so that `sources` in sourcemap can refer to `../src/index.ts` instead of `src/index.ts`
closes #890, closes #889

fix: correct sourcemap with treeshake

---

README.md
docs/README.md

The API docs link in the README.md file has been updated to point to [jsdocs.io](https://jsdocs.io/package/tsup) for all configuration opt

docs: update tsup API docs link [ci skip]

---

src/index.ts
src/rollup.ts

related https://github.com/oven-sh/bun/issues/11760
nothing changes for node, but now tsup can be run on bun: `bun --bun tsup`

fix(dts): terminate worker when work is done

---

src/api-extractor.ts
src/index.ts

Fixed several issues related to `experimentalDts`:
1. Fixed the output type files pointed to non-existent files when `experimentalDts: true` (https://github.com/egoist/tsup/issues/1050)
2. Fixed the DTS files were only generated once when `experimentalDts: true` (https://github.com/egoist/tsup/issues/970#issuecomment-1959545483)

fix: fix `experimentalDts` file cleaning and watching

---

src/esbuild/postcss.ts
src/index.ts
src/options.ts
test/index.test.ts

This PR adds support for an asynchronous `injectStyle` function. 
It also fixes #1194 
We faced an issue where we needed to run custom PostCSS processing in the `injectStyle` function, and certain PostCSS plugins only work in async mode.
Would appreciate a merge, so we can move back to using the `tsup` rather than a fork :)

feat: add support for async `injectStyle`

---

schema.json

The `platform` configuration option allows for `node`, `browser`, and `neutral` ([source](https://github.com/egoist/tsup/blob/ec8301529bfc0d247c4e3037e5136f0a1871de82/src/options.ts#L184)).  This adds `neutral` as a valid option in the schema.json file, which was missing.

fix: add `neutral` value to platform options in `schema.json`

---

src/options.ts

fix https://github.com/egoist/tsup/issues/1111

fix: wider restriction for `target` option

---

schema.json

Hi,
According to the docs at [https://paka.dev/npm/tsup@7.2.0/api#d35d54aca71eb26e](https://paka.dev/npm/tsup@7.2.0/api#d35d54aca71eb26e), the `minify` property should accept either a boolean or `"terser"` as a string.
While using tsup this in the last couple of days, I found that I was getting warnings in my config that `minify` expects a boolean.
I made a local copy of the whole schema file in my project and made the changes in this PR which solved the problem.
Thanks
D

fix: add `terser` value to `minify` option in `schema.json`

---

src/esbuild/postcss.ts

The `await` will automatically handle the following expression, whether a promise or not. 
So there is no need to wrap it with `Promise.resolve` ❤️
> - Non-thenable value: An already-fulfilled Promise is constructed and used.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await#description

refactor: remove unnecessary promise wrapper

---

renovate.json

A new renovate config `.github/renovate.json5` has been added in https://github.com/egoist/tsup/commit/668241895594e656a2cf02babea314bd1256ab89, so this old one `renovate.json` should be removed. It seems that currently, renovate.json is being picked up, which is preventing Renovate PRs from being grouped.

chore: remove duplicated renovate config

---

docs/README.md

ESLint asked me to do `import process from 'node:process'`, and then it took me an hour to realize this feature :(

docs: add notes for `--env` flag

---

src/api-extractor.ts

fix: change `newlineKind` to `lf` for `experimentalDts`

---

src/api-extractor.ts
src/exports.ts
src/index.ts
src/tsc.ts
src/utils.ts
test/__snapshots__/dts.test.ts.snap
test/dts.test.ts
test/experimental-dts.test.ts

fix: support `Node16` and `NodeNext` module resolution in `experimentalDts`

---

src/index.ts
src/utils.ts

fix: run `experimentalDts` only once

---

src/index.ts

fixes #1245
it restores the original behaviour we had while using execa.
The bug was introduced in https://github.com/egoist/tsup/commit/4dd5bfeb2f1973242e2f9700a3061aee9d8af988#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80

fix watching when the onSuccess process never exits

---

pnpm-lock.yaml

update cross-spawn from 7.0.3 to 7.0.6 for security problem

chore: upgrade cross-spawn to 7.0.6

---

package.json
pnpm-lock.yaml
test/index.test.ts

- Substitutes closes #1295 and closes #1294 
- Fixes the test that is failing there:
- The sourcemap file references were fixed in the corresponding [release](https://github.com/evanw/esbuild/releases/tag/v0.25.0)
- Fixes [GHSA-67mh-4wv8-2f99](https://github.com/advisories/GHSA-67mh-4wv8-2f99)
- Deduplicates `esbuild` version via `vite` and `bundle-require`

fix(deps): Upgrading (and deduplicating) esbuild to 0.25

---

assets/esm_shims.js
src/esbuild/index.ts
src/rollup.ts
test/shims.test.ts

fix: make `removeNodeProtocol` work with `shims`

---

docs/README.md
schema.json
src/esbuild/index.ts
src/esbuild/swc.test.ts
src/esbuild/swc.ts
src/options.ts
vitest.config.mts

This PR allow passing custom swc configuration to swcPlugin to solves the following issues: #1291 #1104 #1311
I know this feature isn't aligned with the tsup philosophy to minimize the configuration, but there are some needs that legitimate to introduce `swc` option.
Maybe a better solution can be found based on this PR ;)
When you use legacy TypeScript decorator by enabling `emitDecoratorMetadata` in your tsconfig, tsup will automatically use [SWC](https://swc.rs) to transpile
decorators. In this case, you can give extra swc configuration in the `tsup.config.ts` file.
For example, if you have to define `useDefineForClassFields`, you can do that as follows:
```ts
import { defineConfig } from 'tsup'
export default defineConfig({
entry: ['src/index.ts'],
splitting: false,
sourcemap: true, …
```

feat: allow passing custom swc configuration to swcPlugin

---

README.md

Based on https://x.com/localhost_5173/status/1913448837441806564
@egoist feel free to adapt as needed or close if you think it is not fitting!

chore: add maintenance info in README
