- README.md
Adds the minification flag to the docs.
> chore(docs): Simple Minification docs

- README.md
- src/cli.ts
- src/index.ts
- test/index.test.ts
[issue link](https://github.com/egoist/tsup/issues/97)
try to add sourcemap support
> feat: add --sourcemap flag

- docs/README.md
- package.json
- pnpm-lock.yaml
- src/cli-default.ts
- src/cli-main.ts
- src/cli-node.ts
- src/esbuild/external.ts
- src/index.ts
- test/index.test.ts
> feat: export main cli & add tsup-node command

- src/load.ts
> fix config file with "type": "module"

- docs/README.md
- src/cli-main.ts
- src/esbuild/postcss.ts
- src/index.ts
- src/options.ts
- src/rollup.ts
- src/rollup/ts-resolve.ts
for example:
```typescript
// tsup.config.ts
import { defineConfig } from 'tsup';
export default defineConfig(({ watch }) => ({
minify: watch ? false : true,
}));
```
// and fix some typos
> feat(config): allow conditional config

- src/options.ts
> chore: fix document typo

- src/plugin.ts
#501 fix: plugin without sourceFile
> fix(sourcemap): applySourceMap requires a file path

- src/options.ts
> chore: Issue reference for splitting option

- docs/README.md
Closes https://github.com/egoist/tsup/issues/564
> Add information about .d.ts.map TypeScript  declaration maps

- package.json
- pnpm-lock.yaml
- src/plugins/es5.ts
- test/index.test.ts
Given command below:
```
tsup ./test.ts --minify --format iife --target es5 --globalName test
```
Before PR, result was:
```
function _classCallCheck(instance,Constructor){if(!(instance instanceof Constructor)){throw new TypeError("Cannot call a class as a function")}}function _defineProperties(target,props){for(var i=0;i<props.length;i++){var descriptor=props[i];descriptor.enumerable=descriptor.enumerable||false;descriptor.configurable=true;if("value"in descriptor)descriptor.writable=true;Object.defineProperty(target,descriptor.key,descriptor)}}function _createClass(Constructor,protoProps,staticProps){if(protoProps)_defineProperties(Constructor.prototype,protoProps);if(staticProps)_defineProperties(Constructor,staticProps);return Constructor}var test=function(){var …
```
> feat: improve minification for `--target es5`

- src/options.ts
See https://esbuild.github.io/api/#platform
> fix(types): Add typing for platform: 'neutral'

- src/esbuild/index.ts
- src/esbuild/postcss.ts
> fix: use loader from config for postcss

- src/index.ts
- test/index.test.ts
> feat: respect target config in tsconfig.json

- src/esbuild/index.ts
- src/index.ts
> fix: ensure setContext before run buildStarted

- src/esbuild/postcss.ts
- types.d.ts
> fix: search postcss config from current work dir

- src/rollup.ts
This issue has been fixed by
https://github.com/Swatinem/rollup-plugin-dts/pull/255
> refactor: remove enum fix

- package.json
- pnpm-lock.yaml
- types.d.ts
> chore: upgrade rollup-plugin-hashbang

- src/index.ts
fix: https://github.com/egoist/tsup/issues/976
> fix: process not found on windows

- docs/README.md
Closes https://github.com/egoist/tsup/issues/922
> docs: add information about JavaScript API

- src/load.ts
> feat: add support for `cts` and `mts` config files

- src/options.ts
> chore: add target es2023
